Support for fetching newsletter subscribers INT-377
ActiveCampaign/bigcommerce-api-php pull request #2
Opened 2018-05-21 18:58 UTC by mthommes

### Abstract

For our "accepts marketing" backfill sync script, we need to fetch BigCommerce customers that opted-in to marketing. The problem is this data is not available with the `/customers` endpoint (it is only available at `/customers/subscribers`). This PR updates the BigCommerce SDK to support fetching subscribers.

### Technical Description

The [subscribers endpoint](https://developer.bigcommerce.com/api/v3/customers.html#getsubscribers) is only available with version 3 of the BigCommerce API. Their current SDK does not provide support for using version 3 endpoints, so I had to hack this in there.

### Acceptance Criteria

- [ ] Be able to fetch newsletter subscribers (from checkout) using the BigCommerce SDK

**Team:** @ActiveCampaign/integration

2018-05-21 20:27 UTC, bartboy011 requested changes
Couple of things:

2018-05-21 20:27 UTC, bartboy011 commented on src/Bigcommerce/Api/Client.php
> +        if (strpos($path, '/customers/subscribers') !== false) {
Since we're passing in the `$resource`, we can clean this up and do `if ($resource === 'Subscriber')`

2018-05-21 20:27 UTC, bartboy011 commented on src/Bigcommerce/Api/Client.php
> +        if ($apiVersion == 3) {
Let's do a strict type-comparison here, and add a comment explaining why this is necessary

2018-05-22 10:56 UTC, mthommes commented
@bartboy011 Updated!

2018-05-22 12:57 UTC, bartboy011 approved these changes
Looks good!

2018-05-23 19:38 UTC, merged